spring:
  application:
    name: demo
    version: 1.0.0

  datasource:
    url: jdbc:postgresql://aws-0-eu-north-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.bxyncqawvvfrtzxmqvfa
    password: qwe1@3QWEv2
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
      minimum-idle: 0
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

firebase:
  api-key: AIzaSyADcu2FgZbVq3YHwdOik-n4iEbfaOjMO24

supabase:
  url: https://bxyncqawvvfrtzxmqvfa.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4eW5jcWF3dnZmcnR6eG1xdmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDg3MDQsImV4cCI6MjA2NDY4NDcwNH0.iiG8uC92uzUDuzPQ5sMTj4ilGE5rGV-HQGrg_MXRGDo

server:
  address: 192.168.100.164
  port: 8088